sudo: required
services:
  - docker

before_install:
  - docker build -t clubdeuce/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clubdeuce/react-test npm run test

after_success:
  - docker build -t clubdeuce/multi-client ./client
  - docker build -t clubdeuce/multi-nginx ./nginx
  - docker build -t clubdeuce/multi-server ./server
  - docker build -t clubdeuce/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push clubdeuce/multi-client
  - docker push clubdeuce/multi-nginx
  - docker push clubdeuce/multi-server
  - docker push clubdeuce/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-122018988684"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"